---
sudo: false
language: c
cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc
addons:
  apt:
    packages:
      - libgmp3-dev
matrix:
  include:

    - env: TARGET=x86_64-unkown-linux-gnu
      addons:
        apt:
          update: true
          sources:
            - hvr-ghc
          packages:
            - ghc-8.6.5
            - cabal-install-2.4

    - env: TARGET=x86_64-apple-darwin
      os: osx

before_install:
  - |
    if [ `uname` = "Darwin" ]
    then
      brew install cabal-install
      cabal update
    else
      export PATH=/opt/ghc/bin:$PATH
      cabal update
    fi
  - export PATH=$HOME/.cabal/bin:$PATH

script:
  - cabal build
  - cabal test
  - curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s src foreign-src test bench
